import sqlite3
def add_reader(reader_name):
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM readers ORDER BY id")
    id=c.fetchone()
    id=int(id[0])+1
    c.execute("insert into readers values (?,?)",(id,reader_name))
    conn.commit()
    conn.close()
def print_readers():
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM readers ORDER BY id")
    print(c.fetchall())
    conn.close()
def add_book(title, publish_year,author=None):
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM books ORDER BY id")
    id=c.fetchone()
    id=int(id[0])+1
    c.execute("insert into books values (?,?,?,?)",(id,author,title,publish_year))
    conn.commit()
    conn.close()
def print_books():
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM books ORDER BY id")
    print(c.fetchall())
    conn.close()
def give_book(book_name,reader_name,date):
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM readers where name=:who",{"who":reader_name})
    id_r=c.fetchone()
    id_r=int(id_r[0])
    c.execute("SELECT * FROM books where title=:what",{"what":book_name})
    id_b=c.fetchone()
    id_b=int(id_b[0])
    c.execute("SELECT * FROM records ORDER BY id")
    id=c.fetchone()
    id=int(id[0])+1
    c.execute("insert into records values (?,?,?,?,NULL)",(id,id_r,id_b,date))
    conn.commit()
    conn.close()
def return_book(book_name,reader_name,date):
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM readers where name=:who",{"who":reader_name})
    id_r=c.fetchone()
    id_r=int(id_r[0])
    c.execute("SELECT * FROM books where title=:what",{"what":book_name})
    id_b=c.fetchone()
    id_b=int(id_b[0])
    c.execute("update records set returning_date=:date where reader_id=:id_r and book_id=:id_b",{"id_r":id_r,"id_b":id_b,"date":date})
    conn.commit()
    conn.close()
def print_records():
    conn=sqlite3.connect("books.db")
    c=conn.cursor()
    c.execute("SELECT * FROM records ORDER BY id")
    print(c.fetchall())
    conn.close()
return_book("Слово о полку Игореве","Носова Света","23.02.2024")
print_records()